"""BHOS AF-generated placeholder for BHOS-88.

Bounty title: [Bounty: $85] Disallow /app routes in robots.txt

Generated by real_af at 2026-08-30T02:54:19.277882+00:00.

Requirements:
  - [Bounty: $85] Disallow /app routes in robots.txt

TODO: replace this placeholder with a real implementation.
      The current SCA path will push whatever this file contains.
